#Aashma Dangol
#2408023

4.1 Exercise on Functions

Task 1 – Unit Converter Program

In [1]:
# ==========================================
# 4.1 Task 1 - Unit Converter
# ==========================================

def convert_units(conversion_type, value):
    """
    Converts units between length, weight, and volume.

    Parameters:
    conversion_type (str): Type of conversion
    value (float): Value to convert

    Returns:
    float: Converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type.")


print("Available conversions:")
print("m_to_ft, ft_to_m")
print("kg_to_lbs, lbs_to_kg")
print("l_to_gal, gal_to_l")

choice = input("Enter conversion type: ")

try:
    value = float(input("Enter value: "))
    result = convert_units(choice, value)
    print("Converted value:", result)

except ValueError as e:
    print("Error:", e)

Available conversions:
m_to_ft, ft_to_m
kg_to_lbs, lbs_to_kg
l_to_gal, gal_to_l
Enter conversion type: ft_to_m
Enter value: 6
Converted value: 1.828799941478402


Task 2

In [7]:
# ==========================================
# 4.1 Task 2 - Mathematical Operations on a List
# ==========================================

def list_math_operations():
    """
    Performs sum, average, maximum, or minimum
    on a user-provided list of numbers.

    Returns:
    float: Result of selected mathematical operation
    """

    print("Select an Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter operation (1/2/3/4): ")
    user_input = input("Enter a list of numbers separated by spaces: ")

    try:
        # Convert user input into list of floats
        num_list = [float(x) for x in user_input.split()]

        if not num_list:
            raise ValueError("List cannot be empty.")

        if choice == '1':
            return sum(num_list)

        elif choice == '2':
            return sum(num_list) / len(num_list)

        elif choice == '3':
            return max(num_list)

        elif choice == '4':
            return min(num_list)

        else:
            print("Invalid operation choice.")
            return None

    except ValueError as e:
        print("Error:", e)
        return None


# Call the function and print result
result = list_math_operations()

if result is not None:
    print("Result:", result)

Select an Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter operation (1/2/3/4): 1
Enter a list of numbers separated by spaces: 2 2
Result: 4.0


Exercises on List Manipulation

In [9]:
# ==========================================
# 4.2 Exercise on Lists
# List Slicing Operations
# ==========================================

# 1. Extract Every Other Element
def extract_every_other(lst):
    """
    Returns every second element from the list.
    """
    return lst[::2]


# 2. Slice a Sublist
def get_sublist(lst, start, end):
    """
    Returns a sublist from index 'start' to 'end' (inclusive).
    """
    return lst[start:end+1]


# 3. Remove the First and Last Elements
def remove_first_last(lst):
    """
    Removes the first and last elements of a list.
    Returns empty list if length < 2.
    """
    if len(lst) < 2:
        return []
    return lst[1:-1]


# 4. Get the First n Elements
def get_first_n(lst, n):
    """
    Returns the first n elements of the list.
    """
    return lst[:n]


# 5. Extract Last n Elements
def get_last_n(lst, n):
    """
    Returns the last n elements of the list.
    """
    if n == 0:
        return []
    return lst[-n:]


# 6. Reverse Order Skipping One Element
def reverse_skip(lst):
    """
    Returns elements in reverse order,
    skipping one element in between.
    """
    return lst[-2::-2]


# -----------------------------
# Test Cases
# -----------------------------

sample_list = [1, 2, 3, 4, 5, 6]

print("Original List:", sample_list)
print("Extract every other:", extract_every_other(sample_list))
print("Sublist (1 to 4):", get_sublist(sample_list, 1, 4))
print("Remove first and last:", remove_first_last(sample_list))
print("First 3 elements:", get_first_n(sample_list, 3))
print("Last 2 elements:", get_last_n(sample_list, 2))
print("Reverse skip:", reverse_skip(sample_list))

Original List: [1, 2, 3, 4, 5, 6]
Extract every other: [1, 3, 5]
Sublist (1 to 4): [2, 3, 4, 5]
Remove first and last: [2, 3, 4, 5]
First 3 elements: [1, 2, 3]
Last 2 elements: [5, 6]
Reverse skip: [5, 3, 1]


Exercises on Nested Lists

In [10]:
# 1. Flatten a Nested List (1-Level Depth)
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(item)
        else:
            flat_list.append(item)
    return flat_list

# 2. Accessing Nested List Elements based on indices list
def access_nested_element(lst, indices):
    result = lst
    try:
        for idx in indices:
            result = result[idx]
        return result
    except (IndexError, TypeError):
        return "Invalid indices for the given list."

# 3. Sum of All Elements in a Nested List (Regardless of Depth)
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        elif isinstance(item, (int, float)):
            total += item
    return total

# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Test Cases
nested = [[1, 2], [3, [4, 5]], 6]
print("Flatten 1 level:", flatten([[1, 2], [3, 4], [5]]))
print("Access element at [1, 2]:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print("Sum of nested:", sum_nested(nested))
print("Count occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

Flatten 1 level: [1, 2, 3, 4, 5]
Access element at [1, 2]: 6
Sum of nested: 21
Count occurrences of 2: 3


Basic Vector and Matrix Operations with NumPy

NumPy Array Creation

In [12]:
# ==========================================
# NumPy Problem 1: Array Creation
# ==========================================

import numpy as np

print("---- Problem 1: Array Creation ----")

# Create different types of arrays
empty_arr = np.empty((2, 2))
ones_arr = np.ones((4, 2))
full_arr = np.full((3, 3), 7)
zeros_like_arr = np.zeros_like(ones_arr)
ones_like_arr = np.ones_like(empty_arr)

# Create array from list
new_list = [1, 2, 3, 4]
np_from_list = np.array(new_list)

print("Empty Array:\n", empty_arr)
print("Ones Array:\n", ones_arr)
print("Full Array:\n", full_arr)
print("Zeros Like:\n", zeros_like_arr)
print("Ones Like:\n", ones_like_arr)
print("Array from List:\n", np_from_list)

---- Problem 1: Array Creation ----
Empty Array:
 [[4.4e-323 5.4e-323]
 [4.9e-323 5.9e-323]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Ones Like:
 [[1. 1.]
 [1. 1.]]
Array from List:
 [1 2 3 4]


NumPy Array Manipulation

In [13]:
# ==========================================
# NumPy Problem 2: Array Manipulation
# ==========================================

print("---- Problem 2: Array Manipulation ----")

range_arr = np.arange(10, 50)
matrix_3x3 = np.arange(0, 9).reshape((3, 3))
identity_matrix = np.eye(3)

random_arr = np.random.random(30)
mean_val = random_arr.mean()

print("Range Array (10 to 49):\n", range_arr)
print("3x3 Matrix:\n", matrix_3x3)
print("Identity Matrix:\n", identity_matrix)
print("Mean of Random Array:", mean_val)

---- Problem 2: Array Manipulation ----
Range Array (10 to 49):
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of Random Array: 0.4501838081592181


NumPy Array Operations

In [14]:
# ==========================================
# NumPy Problem 3: Array Operations
# ==========================================

print("---- Problem 3: Array Operations ----")

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Basic operations
print("Addition:\n", x + y)
print("Subtraction:\n", x - y)
print("Multiply by 3:\n", x * 3)
print("Square of elements:\n", np.square(x))

# Dot products
print("Dot product (v · w):", np.dot(v, w))
print("Dot product (x · v):", np.dot(x, v))
print("Dot product (x · y):\n", np.dot(x, y))

# Concatenation
print("Concatenate x and y (axis=0):\n", np.concatenate((x, y), axis=0))
print("Column stack v and w:\n", np.column_stack((v, w)))

# Intentional error handling
try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError while concatenating x and v:")
    print("Caught Error:", e)
    print("Explanation: x is 2D (2x2) and v is 1D (2,).")
    print("To concatenate, v must be reshaped like v.reshape(1,2).")

---- Problem 3: Array Operations ----
Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiply by 3:
 [[ 3  6]
 [ 9 15]]
Square of elements:
 [[ 1  4]
 [ 9 25]]
Dot product (v · w): 219
Dot product (x · v): [29 77]
Dot product (x · y):
 [[19 22]
 [50 58]]
Concatenate x and y (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Column stack v and w:
 [[ 9 11]
 [10 12]]

Error while concatenating x and v:
Caught Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2D (2x2) and v is 1D (2,).
To concatenate, v must be reshaped like v.reshape(1,2).
