#Aashma Dangol
#2408023

4.1 Exercise on Functions

Task 1 – Unit Converter Program

In [2]:
# ==========================================
# 4.1 Task 1 - Unit Converter
# ==========================================

def convert_units(conversion_type, value):
    """
    Converts units between length, weight, and volume.

    Parameters:
    conversion_type (str): Type of conversion
    value (float): Value to convert

    Returns:
    float: Converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type.")


print("Available conversions:")
print("m_to_ft, ft_to_m")
print("kg_to_lbs, lbs_to_kg")
print("l_to_gal, gal_to_l")

choice = input("Enter conversion type: ")

try:
    value = float(input("Enter value: "))
    result = convert_units(choice, value)
    print("Converted value:", result)

except ValueError as e:
    print("Error:", e)

Available conversions:
m_to_ft, ft_to_m
kg_to_lbs, lbs_to_kg
l_to_gal, gal_to_l


KeyboardInterrupt: Interrupted by user

Task 2

In [ ]:
# ==========================================
# 4.1 Task 2 - Mathematical Operations on a List
# ==========================================

def list_math_operations():
    """
    Performs sum, average, maximum, or minimum
    on a user-provided list of numbers.

    Returns:
    float: Result of selected mathematical operation
    """

    print("Select an Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter operation (1/2/3/4): ")
    user_input = input("Enter a list of numbers separated by spaces: ")

    try:
        # Convert user input into list of floats
        num_list = [float(x) for x in user_input.split()]

        if not num_list:
            raise ValueError("List cannot be empty.")

        if choice == '1':
            return sum(num_list)

        elif choice == '2':
            return sum(num_list) / len(num_list)

        elif choice == '3':
            return max(num_list)

        elif choice == '4':
            return min(num_list)

        else:
            print("Invalid operation choice.")
            return None

    except ValueError as e:
        print("Error:", e)
        return None


# Call the function and print result
result = list_math_operations()

if result is not None:
    print("Result:", result)

Exercises on List Manipulation

In [ ]:
# ==========================================
# 4.2 Exercise on Lists
# List Slicing Operations
# ==========================================

# 1. Extract Every Other Element
def extract_every_other(lst):
    """
    Returns every second element from the list.
    """
    return lst[::2]


# 2. Slice a Sublist
def get_sublist(lst, start, end):
    """
    Returns a sublist from index 'start' to 'end' (inclusive).
    """
    return lst[start:end+1]


# 3. Remove the First and Last Elements
def remove_first_last(lst):
    """
    Removes the first and last elements of a list.
    Returns empty list if length < 2.
    """
    if len(lst) < 2:
        return []
    return lst[1:-1]


# 4. Get the First n Elements
def get_first_n(lst, n):
    """
    Returns the first n elements of the list.
    """
    return lst[:n]


# 5. Extract Last n Elements
def get_last_n(lst, n):
    """
    Returns the last n elements of the list.
    """
    if n == 0:
        return []
    return lst[-n:]


# 6. Reverse Order Skipping One Element
def reverse_skip(lst):
    """
    Returns elements in reverse order,
    skipping one element in between.
    """
    return lst[-2::-2]


# -----------------------------
# Test Cases
# -----------------------------

sample_list = [1, 2, 3, 4, 5, 6]

print("Original List:", sample_list)
print("Extract every other:", extract_every_other(sample_list))
print("Sublist (1 to 4):", get_sublist(sample_list, 1, 4))
print("Remove first and last:", remove_first_last(sample_list))
print("First 3 elements:", get_first_n(sample_list, 3))
print("Last 2 elements:", get_last_n(sample_list, 2))
print("Reverse skip:", reverse_skip(sample_list))

Exercises on Nested Lists

In [ ]:
# 1. Flatten a Nested List (1-Level Depth)
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(item)
        else:
            flat_list.append(item)
    return flat_list

# 2. Accessing Nested List Elements based on indices list
def access_nested_element(lst, indices):
    result = lst
    try:
        for idx in indices:
            result = result[idx]
        return result
    except (IndexError, TypeError):
        return "Invalid indices for the given list."

# 3. Sum of All Elements in a Nested List (Regardless of Depth)
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        elif isinstance(item, (int, float)):
            total += item
    return total

# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Test Cases
nested = [[1, 2], [3, [4, 5]], 6]
print("Flatten 1 level:", flatten([[1, 2], [3, 4], [5]]))
print("Access element at [1, 2]:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print("Sum of nested:", sum_nested(nested))
print("Count occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

Basic Vector and Matrix Operations with NumPy

NumPy Array Creation

In [ ]:
# ==========================================
# NumPy Problem 1: Array Creation
# ==========================================

import numpy as np

print("---- Problem 1: Array Creation ----")

# Create different types of arrays
empty_arr = np.empty((2, 2))
ones_arr = np.ones((4, 2))
full_arr = np.full((3, 3), 7)
zeros_like_arr = np.zeros_like(ones_arr)
ones_like_arr = np.ones_like(empty_arr)

# Create array from list
new_list = [1, 2, 3, 4]
np_from_list = np.array(new_list)

print("Empty Array:\n", empty_arr)
print("Ones Array:\n", ones_arr)
print("Full Array:\n", full_arr)
print("Zeros Like:\n", zeros_like_arr)
print("Ones Like:\n", ones_like_arr)
print("Array from List:\n", np_from_list)

NumPy Array Manipulation

In [ ]:
# ==========================================
# NumPy Problem 2: Array Manipulation
# ==========================================

print("---- Problem 2: Array Manipulation ----")

range_arr = np.arange(10, 50)
matrix_3x3 = np.arange(0, 9).reshape((3, 3))
identity_matrix = np.eye(3)

random_arr = np.random.random(30)
mean_val = random_arr.mean()

print("Range Array (10 to 49):\n", range_arr)
print("3x3 Matrix:\n", matrix_3x3)
print("Identity Matrix:\n", identity_matrix)
print("Mean of Random Array:", mean_val)

NumPy Array Operations

In [ ]:
# ==========================================
# NumPy Problem 3: Array Operations
# ==========================================

print("---- Problem 3: Array Operations ----")

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Basic operations
print("Addition:\n", x + y)
print("Subtraction:\n", x - y)
print("Multiply by 3:\n", x * 3)
print("Square of elements:\n", np.square(x))

# Dot products
print("Dot product (v · w):", np.dot(v, w))
print("Dot product (x · v):", np.dot(x, v))
print("Dot product (x · y):\n", np.dot(x, y))

# Concatenation
print("Concatenate x and y (axis=0):\n", np.concatenate((x, y), axis=0))
print("Column stack v and w:\n", np.column_stack((v, w)))

# Intentional error handling
try:
    np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError while concatenating x and v:")
    print("Caught Error:", e)
    print("Explanation: x is 2D (2x2) and v is 1D (2,).")
    print("To concatenate, v must be reshaped like v.reshape(1,2).")

Problem 4: Matrix Operations

In [1]:
# Import Numpy
import numpy as np

# -----------------------------
# PART 1: Matrix Operations
# -----------------------------
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# 1️⃣ Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("\nInverse of A (A^-1):\n", A_inv)

I = np.dot(A, A_inv)
print("\nA * A^-1 =\n", I)

# 2️⃣ Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nA*B =\n", AB)
print("B*A =\n", BA)
print("Is A*B equal to B*A? ", np.array_equal(AB, BA))

# 3️⃣ Prove (AB)^T = B^T * A^T
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T =\n", AB_T)
print("B^T * A^T =\n", BT_AT)
print("Does (AB)^T equal B^T * A^T? ", np.array_equal(AB_T, BT_AT))

# -----------------------------
# PART 2: Solve Linear Equations using Inverse
# -----------------------------
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Coefficient matrix
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

# Constants vector
B_eq = np.array([-1, -3, 9])

# Solve using inverse
X_inv = np.dot(np.linalg.inv(A_eq), B_eq)
print("\nSolution using A^-1 * B:", X_inv)

# Solve using np.linalg.solve (recommended)
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve:", X_solve)

Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]

Inverse of A (A^-1):
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

A*B =
 [[23 13]
 [51 29]]
B*A =
 [[36 44]
 [13 16]]
Is A*B equal to B*A?  False

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Does (AB)^T equal B^T * A^T?  True

Solution using A^-1 * B: [ 2.  1. -2.]
Solution using np.linalg.solve: [ 2.  1. -2.]


In [3]:
# Experiment: How Fast is NumPy?

import numpy as np
import time

# -----------------------------
# 1️⃣ Element-wise Addition
# -----------------------------
size = 1_000_000

# Using Python lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print(f"Python list addition time: {end - start:.4f} seconds")

# Using NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print(f"NumPy array addition time: {end - start:.4f} seconds")

# -----------------------------
# 2️⃣ Element-wise Multiplication
# -----------------------------

# Python lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print(f"Python list multiplication time: {end - start:.4f} seconds")

# NumPy arrays
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print(f"NumPy array multiplication time: {end - start:.4f} seconds")

# -----------------------------
# 3️⃣ Dot Product
# -----------------------------

# Python lists
start = time.time()
dot_list = sum([list1[i] * list2[i] for i in range(size)])
end = time.time()
print(f"Python list dot product time: {end - start:.4f} seconds")

# NumPy arrays
start = time.time()
dot_arr = np.dot(arr1, arr2)
end = time.time()
print(f"NumPy array dot product time: {end - start:.4f} seconds")

# -----------------------------
# 4️⃣ Matrix Multiplication (1000 x 1000)
# -----------------------------
matrix_size = 1000

# Python lists
matrix1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i-j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
# Manual matrix multiplication using loops
result = [[0]*matrix_size for _ in range(matrix_size)]
for i in range(matrix_size):
    for j in range(matrix_size):
        for k in range(matrix_size):
            result[i][j] += matrix1[i][k] * matrix2[k][j]
end = time.time()
print(f"Python list matrix multiplication time: {end - start:.4f} seconds")

# NumPy arrays
mat1 = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)
mat2 = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)

start = time.time()
mat_result = np.matmul(mat1, mat2)  # or mat1 @ mat2
end = time.time()
print(f"NumPy array matrix multiplication time: {end - start:.4f} seconds")

Python list addition time: 0.1155 seconds
NumPy array addition time: 0.0055 seconds
Python list multiplication time: 0.1120 seconds
NumPy array multiplication time: 0.0059 seconds
Python list dot product time: 0.1620 seconds
NumPy array dot product time: 0.0019 seconds
Python list matrix multiplication time: 382.5164 seconds
NumPy array matrix multiplication time: 2.5386 seconds
